name: deploy microservices 

on:
  workflow_dispatch:
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.2

      - name: configure AWS Cli
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.7.4

      - name: terraform init
        working-directory: Terraform
        run: terraform init

      - name: terraform plan
        working-directory: Terraform
        run: terraform plan

      - name: terraform apply
        working-directory: Terraform
        run: terraform apply -auto-approve

  microservices:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.2

      - name: configure AWS Cli
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: connect to EKS cluster
        run: 
          aws eks update-kubeconfig --region us-east-2 --name microservices

      - name: Deploy example Microservice
        run: kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/release/kubernetes-manifests.yaml
        
      - name: check deployment status
        run: kubectl get all -o wide -A 

          
