name: microservices eks 

on:
  workflow_dispatch:
    inputs:
      apply_or_destroy:
        type: choice
        description: Run terraform apply or destroy
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@4.1.2

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@4.0.2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: setup terraform
        uses: hashicorp/setup-terraform@2.0.3
        with:
          terraform_version: 1.7.4

      - name: terraform init
        working-directory: Terraform
        run: terraform init

      - name: terraform plan
        working-directory: Terraform
        run: terraform plan

      - name: terraform apply
        if: ${{ github.event.inputs.apply_or_destroy == 'apply' }}
        working-directory: Terraform
        run: terraform apply
        
      - name: terraform destroy
        if: ${{ github.event.inputs.apply_or_destroy == 'destroy' }}
        working-directory: Terraform
        run: terraform init

          
